FROM maven:3.6.3-openjdk-15 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM openjdk:8-jre-alpine
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/target/uporabniki-1.0.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "uporabniki-1.0.0-SNAPSHOT.jar"]